export declare const API_BASE_URL: string;
export declare const apiFetch: (endpoint: string, options?: RequestInit) => Promise<Response>;
export declare const API_ENDPOINTS: {
    readonly LOGIN: "/api/login";
    readonly SIGNUP: "/api/signup";
    readonly LOGOUT: "/api/logout";
    readonly SUBSCRIPTIONS: "/api/subscriptions";
    readonly EMPLOYEES: "/api/employees";
    readonly ANALYTICS_DASHBOARD: "/api/analytics/dashboard";
    readonly ANALYTICS_TRENDS: "/api/analytics/trends";
    readonly ANALYTICS_CATEGORIES: "/api/analytics/categories";
    readonly COMPLIANCE_LIST: "/api/compliance/list";
    readonly COMPLIANCE_INSERT: "/api/compliance/insert";
    readonly LEDGER_INSERT: "/api/ledger/insert";
    readonly PAYMENT: "/api/payment";
    readonly CONFIG_FIELDS: "/api/config/fields";
    readonly CONFIG_COMPLIANCE_FIELDS: "/api/config/compliance-fields";
    readonly COMPANY_CATEGORIES: "/api/company/categories";
    readonly COMPANY_DEPARTMENTS: "/api/company/departments";
    readonly CURRENCIES: "/api/currencies";
};
