export type CurrencyOption = {
  code: string;
  description: string;
  symbol: string;
};

// Map currency code to ISO country code for flag rendering
export const getCountryCodeForCurrency = (code: string): string | undefined => {
  const map: Record<string, string> = {
    AED: "AE",
    AFN: "AF",
    ALL: "AL",
    AMD: "AM",
    ANG: "CW",
    AOA: "AO",
    ARS: "AR",
    AUD: "AU",
    AWG: "AW",
    AZN: "AZ",
    BAM: "BA",
    BBD: "BB",
    BDT: "BD",
    BGN: "BG",
    BHD: "BH",
    BIF: "BI",
    BMD: "BM",
    BND: "BN",
    BOB: "BO",
    BRL: "BR",
    BSD: "BS",
    BTN: "BT",
    BWP: "BW",
    BYN: "BY",
    BZD: "BZ",
    CAD: "CA",
    CDF: "CD",
    CHF: "CH",
    CLP: "CL",
    CNY: "CN",
    COP: "CO",
    CRC: "CR",
    CUP: "CU",
    CVE: "CV",
    CZK: "CZ",
    DJF: "DJ",
    DKK: "DK",
    DOP: "DO",
    DZD: "DZ",
    EGP: "EG",
    ERN: "ER",
    ETB: "ET",
    EUR: "EU",
    FJD: "FJ",
    FKP: "FK",
    GBP: "GB",
    GEL: "GE",
    GHS: "GH",
    GIP: "GI",
    GMD: "GM",
    GNF: "GN",
    GTQ: "GT",
    GYD: "GY",
    HKD: "HK",
    HNL: "HN",
    HRK: "HR",
    HTG: "HT",
    HUF: "HU",
    IDR: "ID",
    ILS: "IL",
    INR: "IN",
    IQD: "IQ",
    IRR: "IR",
    ISK: "IS",
    JMD: "JM",
    JOD: "JO",
    JPY: "JP",
    KES: "KE",
    KGS: "KG",
    KHR: "KH",
    KMF: "KM",
    KWD: "KW",
    KZT: "KZ",
    LAK: "LA",
    LBP: "LB",
    LKR: "LK",
    LRD: "LR",
    LSL: "LS",
    LYD: "LY",
    MAD: "MA",
    MDL: "MD",
    MGA: "MG",
    MKD: "MK",
    MMK: "MM",
    MNT: "MN",
    MOP: "MO",
    MRU: "MR",
    MUR: "MU",
    MVR: "MV",
    MWK: "MW",
    MXN: "MX",
    MYR: "MY",
    MZN: "MZ",
    NAD: "NA",
    NGN: "NG",
    NIO: "NI",
    NOK: "NO",
    NPR: "NP",
    NZD: "NZ",
    OMR: "OM",
    PAB: "PA",
    PEN: "PE",
    PGK: "PG",
    PHP: "PH",
    PKR: "PK",
    PLN: "PL",
    PYG: "PY",
    QAR: "QA",
    RON: "RO",
    RSD: "RS",
    RUB: "RU",
    RWF: "RW",
    SAR: "SA",
    SBD: "SB",
    SCR: "SC",
    SDG: "SD",
    SEK: "SE",
    SGD: "SG",
    SHP: "SH",
    SLE: "SL",
    SOS: "SO",
    SRD: "SR",
    SSP: "SS",
    STN: "ST",
    SZL: "SZ",
    THB: "TH",
    TJS: "TJ",
    TMT: "TM",
    TND: "TN",
    TOP: "TO",
    TRY: "TR",
    TTD: "TT",
    TVD: "TV",
    TWD: "TW",
    TZS: "TZ",
    UAH: "UA",
    UGX: "UG",
    USD: "US",
    UYU: "UY",
    UZS: "UZ",
    VES: "VE",
    VND: "VN",
    VUV: "VU",
    WST: "WS",
    XAF: "CF",
    XCD: "AG",
    XOF: "SN",
    XPF: "PF",
    YER: "YE",
    ZAR: "ZA",
    ZMW: "ZM",
    ZWL: "ZW",
  };

  return map[code as keyof typeof map];
};

// Complete currency list for autocomplete (mirrors Configuration → Currency tab)
export const currencyList: CurrencyOption[] = [
  { code: "AED", description: "UAE Dirham", symbol: "د.إ" },
  { code: "AFN", description: "Afghan Afghani", symbol: "؋" },
  { code: "ALL", description: "Albanian Lek", symbol: "L" },
  { code: "AMD", description: "Armenian Dram", symbol: "֏" },
  { code: "ANG", description: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { code: "AOA", description: "Angolan Kwanza", symbol: "Kz" },
  { code: "ARS", description: "Argentine Peso", symbol: "$" },
  { code: "AUD", description: "Australian Dollar", symbol: "A$" },
  { code: "AWG", description: "Aruban Florin", symbol: "ƒ" },
  { code: "AZN", description: "Azerbaijani Manat", symbol: "₼" },
  { code: "BAM", description: "Bosnia and Herzegovina Convertible Mark", symbol: "KM" },
  { code: "BBD", description: "Barbadian Dollar", symbol: "Bds$" },
  { code: "BDT", description: "Bangladeshi Taka", symbol: "৳" },
  { code: "BGN", description: "Bulgarian Lev", symbol: "лв" },
  { code: "BHD", description: "Bahraini Dinar", symbol: ".د.ب" },
  { code: "BIF", description: "Burundian Franc", symbol: "FBu" },
  { code: "BMD", description: "Bermudian Dollar", symbol: "$" },
  { code: "BND", description: "Brunei Dollar", symbol: "B$" },
  { code: "BOB", description: "Bolivian Boliviano", symbol: "Bs." },
  { code: "BRL", description: "Brazilian Real", symbol: "R$" },
  { code: "BSD", description: "Bahamian Dollar", symbol: "$" },
  { code: "BTN", description: "Bhutanese Ngultrum", symbol: "Nu." },
  { code: "BWP", description: "Botswana Pula", symbol: "P" },
  { code: "BYN", description: "Belarusian Ruble", symbol: "Br" },
  { code: "BZD", description: "Belize Dollar", symbol: "BZ$" },
  { code: "CAD", description: "Canadian Dollar", symbol: "C$" },
  { code: "CDF", description: "Congolese Franc", symbol: "FC" },
  { code: "CHF", description: "Swiss Franc", symbol: "CHF" },
  { code: "CLP", description: "Chilean Peso", symbol: "$" },
  { code: "CNY", description: "Chinese Yuan", symbol: "¥" },
  { code: "COP", description: "Colombian Peso", symbol: "$" },
  { code: "CRC", description: "Costa Rican Colón", symbol: "₡" },
  { code: "CUP", description: "Cuban Peso", symbol: "$" },
  { code: "CVE", description: "Cape Verdean Escudo", symbol: "$" },
  { code: "CZK", description: "Czech Koruna", symbol: "Kč" },
  { code: "DJF", description: "Djiboutian Franc", symbol: "Fdj" },
  { code: "DKK", description: "Danish Krone", symbol: "kr" },
  { code: "DOP", description: "Dominican Peso", symbol: "RD$" },
  { code: "DZD", description: "Algerian Dinar", symbol: "دج" },
  { code: "EGP", description: "Egyptian Pound", symbol: "£" },
  { code: "ERN", description: "Eritrean Nakfa", symbol: "Nkf" },
  { code: "ETB", description: "Ethiopian Birr", symbol: "Br" },
  { code: "EUR", description: "Euro", symbol: "€" },
  { code: "FJD", description: "Fijian Dollar", symbol: "FJ$" },
  { code: "FKP", description: "Falkland Islands Pound", symbol: "£" },
  { code: "FOK", description: "Faroese Króna", symbol: "kr" },
  { code: "GBP", description: "British Pound Sterling", symbol: "£" },
  { code: "GEL", description: "Georgian Lari", symbol: "₾" },
  { code: "GGP", description: "Guernsey Pound", symbol: "£" },
  { code: "GHS", description: "Ghanaian Cedi", symbol: "₵" },
  { code: "GIP", description: "Gibraltar Pound", symbol: "£" },
  { code: "GMD", description: "Gambian Dalasi", symbol: "D" },
  { code: "GNF", description: "Guinean Franc", symbol: "FG" },
  { code: "GTQ", description: "Guatemalan Quetzal", symbol: "Q" },
  { code: "GYD", description: "Guyanese Dollar", symbol: "G$" },
  { code: "HKD", description: "Hong Kong Dollar", symbol: "HK$" },
  { code: "HNL", description: "Honduran Lempira", symbol: "L" },
  { code: "HRK", description: "Croatian Kuna", symbol: "kn" },
  { code: "HTG", description: "Haitian Gourde", symbol: "G" },
  { code: "HUF", description: "Hungarian Forint", symbol: "Ft" },
  { code: "IDR", description: "Indonesian Rupiah", symbol: "Rp" },
  { code: "ILS", description: "Israeli New Shekel", symbol: "₪" },
  { code: "IMP", description: "Isle of Man Pound", symbol: "£" },
  { code: "INR", description: "Indian Rupee", symbol: "₹" },
  { code: "IQD", description: "Iraqi Dinar", symbol: "ع.د" },
  { code: "IRR", description: "Iranian Rial", symbol: "﷼" },
  { code: "ISK", description: "Icelandic Króna", symbol: "kr" },
  { code: "JEP", description: "Jersey Pound", symbol: "£" },
  { code: "JMD", description: "Jamaican Dollar", symbol: "J$" },
  { code: "JOD", description: "Jordanian Dinar", symbol: "د.ا" },
  { code: "JPY", description: "Japanese Yen", symbol: "¥" },
  { code: "KES", description: "Kenyan Shilling", symbol: "KSh" },
  { code: "KGS", description: "Kyrgyzstani Som", symbol: "лв" },
  { code: "KHR", description: "Cambodian Riel", symbol: "៛" },
  { code: "KID", description: "Kiribati Dollar", symbol: "$" },
  { code: "KMF", description: "Comorian Franc", symbol: "CF" },
  { code: "KRW", description: "South Korean Won", symbol: "₩" },
  { code: "KWD", description: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "KYD", description: "Cayman Islands Dollar", symbol: "CI$" },
  { code: "KZT", description: "Kazakhstani Tenge", symbol: "₸" },
  { code: "LAK", description: "Lao Kip", symbol: "₭" },
  { code: "LBP", description: "Lebanese Pound", symbol: "ل.ل" },
  { code: "LKR", description: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "LRD", description: "Liberian Dollar", symbol: "L$" },
  { code: "LSL", description: "Lesotho Loti", symbol: "L" },
  { code: "LYD", description: "Libyan Dinar", symbol: "ل.د" },
  { code: "MAD", description: "Moroccan Dirham", symbol: "د.م." },
  { code: "MDL", description: "Moldovan Leu", symbol: "L" },
  { code: "MGA", description: "Malagasy Ariary", symbol: "Ar" },
  { code: "MKD", description: "Macedonian Denar", symbol: "ден" },
  { code: "MMK", description: "Myanmar Kyat", symbol: "K" },
  { code: "MNT", description: "Mongolian Tögrög", symbol: "₮" },
  { code: "MOP", description: "Macanese Pataca", symbol: "MOP$" },
  { code: "MRU", description: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "MUR", description: "Mauritian Rupee", symbol: "Rs" },
  { code: "MVR", description: "Maldivian Rufiyaa", symbol: "Rf" },
  { code: "MWK", description: "Malawian Kwacha", symbol: "MK" },
  { code: "MXN", description: "Mexican Peso", symbol: "$" },
  { code: "MYR", description: "Malaysian Ringgit", symbol: "RM" },
  { code: "MZN", description: "Mozambican Metical", symbol: "MT" },
  { code: "NAD", description: "Namibian Dollar", symbol: "N$" },
  { code: "NGN", description: "Nigerian Naira", symbol: "₦" },
  { code: "NIO", description: "Nicaraguan Córdoba", symbol: "C$" },
  { code: "NOK", description: "Norwegian Krone", symbol: "kr" },
  { code: "NPR", description: "Nepalese Rupee", symbol: "Rs" },
  { code: "NZD", description: "New Zealand Dollar", symbol: "NZ$" },
  { code: "OMR", description: "Omani Rial", symbol: "﷼" },
  { code: "PAB", description: "Panamanian Balboa", symbol: "B/." },
  { code: "PEN", description: "Peruvian Sol", symbol: "S/" },
  { code: "PGK", description: "Papua New Guinean Kina", symbol: "K" },
  { code: "PHP", description: "Philippine Peso", symbol: "₱" },
  { code: "PKR", description: "Pakistani Rupee", symbol: "Rs" },
  { code: "PLN", description: "Polish Złoty", symbol: "zł" },
  { code: "PYG", description: "Paraguayan Guaraní", symbol: "₲" },
  { code: "QAR", description: "Qatari Riyal", symbol: "ر.ق" },
  { code: "RON", description: "Romanian Leu", symbol: "lei" },
  { code: "RSD", description: "Serbian Dinar", symbol: "дин." },
  { code: "RUB", description: "Russian Ruble", symbol: "₽" },
  { code: "RWF", description: "Rwandan Franc", symbol: "RF" },
  { code: "SAR", description: "Saudi Riyal", symbol: "ر.س" },
  { code: "SBD", description: "Solomon Islands Dollar", symbol: "SI$" },
  { code: "SCR", description: "Seychellois Rupee", symbol: "Rs" },
  { code: "SDG", description: "Sudanese Pound", symbol: "£" },
  { code: "SEK", description: "Swedish Krona", symbol: "kr" },
  { code: "SGD", description: "Singapore Dollar", symbol: "S$" },
  { code: "SHP", description: "Saint Helena Pound", symbol: "£" },
  { code: "SLE", description: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SOS", description: "Somali Shilling", symbol: "Sh" },
  { code: "SRD", description: "Surinamese Dollar", symbol: "$" },
  { code: "SSP", description: "South Sudanese Pound", symbol: "£" },
  { code: "STN", description: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "SYP", description: "Syrian Pound", symbol: "£" },
  { code: "SZL", description: "Eswatini Lilangeni", symbol: "L" },
  { code: "THB", description: "Thai Baht", symbol: "฿" },
  { code: "TJS", description: "Tajikistani Somoni", symbol: "SM" },
  { code: "TMT", description: "Turkmenistani Manat", symbol: "m" },
  { code: "TND", description: "Tunisian Dinar", symbol: "د.ت" },
  { code: "TOP", description: "Tongan Paʻanga", symbol: "T$" },
  { code: "TRY", description: "Turkish Lira", symbol: "₺" },
  { code: "TTD", description: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { code: "TVD", description: "Tuvaluan Dollar", symbol: "$" },
  { code: "TWD", description: "New Taiwan Dollar", symbol: "NT$" },
  { code: "TZS", description: "Tanzanian Shilling", symbol: "Sh" },
  { code: "UAH", description: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "UGX", description: "Ugandan Shilling", symbol: "USh" },
  { code: "USD", description: "United States Dollar", symbol: "$" },
  { code: "UYU", description: "Uruguayan Peso", symbol: "$U" },
  { code: "UZS", description: "Uzbekistani So'm", symbol: "лв" },
  { code: "VES", description: "Venezuelan Bolívar", symbol: "Bs." },
  { code: "VND", description: "Vietnamese Đồng", symbol: "₫" },
  { code: "VUV", description: "Vanuatu Vatu", symbol: "Vt" },
  { code: "WST", description: "Samoan Tala", symbol: "T" },
  { code: "XAF", description: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XCD", description: "East Caribbean Dollar", symbol: "EC$" },
  { code: "XOF", description: "West African CFA Franc", symbol: "CFA" },
  { code: "XPF", description: "CFP Franc", symbol: "₣" },
  { code: "YER", description: "Yemeni Rial", symbol: "﷼" },
  { code: "ZAR", description: "South African Rand", symbol: "R" },
  { code: "ZMW", description: "Zambian Kwacha", symbol: "ZK" },
  { code: "ZWL", description: "Zimbabwean Dollar", symbol: "Z$" },
];
