const XLSX = require('xlsx');
const path = require('path');

function generateUserGuide() {
  const wb = XLSX.utils.book_new();

  // ===== INTRODUCTION SHEET =====
  const introData = [
    ['SUBSCRIPTION TRACKER - USER GUIDE'],
    [''],
    ['Welcome to Subscription Tracker!'],
    [''],
    ['TABLE OF CONTENTS'],
    ['1. Introduction & Getting Started'],
    ['2. Login & Signup Process'],
    ['3. Company Details'],
    ['4. Setup & Configuration'],
    ['5. Subscription Management'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['1. INTRODUCTION & GETTING STARTED'],
    [''],
    ['Getting Started:'],
    ['By clicking the link below, you can access the Subscription Tracker platform to login or sign up:'],
    ['🔗 https://subscription-management-6uje.onrender.com'],
    [''],
    ['What is Subscription Tracker?'],
    ['Subscription Tracker is a comprehensive platform designed to help businesses manage their subscriptions,'],
    ['track expenses, handle compliance, and maintain payment methods efficiently.'],
    [''],
    ['Key Features:'],
    ['• Multi-tenant architecture - Each company has isolated data'],
    ['• Subscription management with automatic reminders'],
    ['• Payment method tracking'],
    ['• Currency management and conversion'],
    ['• Compliance and government license tracking'],
    ['• User management and role-based access'],
    ['• Advanced reporting and analytics'],
    [''],
    ['System Requirements:'],
    ['• Modern web browser (Chrome, Firefox, Edge, Safari)'],
    ['• Internet connection'],
    ['• Valid business email address'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['2. LOGIN & SIGNUP PROCESS'],
    [''],
    ['───────────────────────────────────────────────────────────────────────────────────'],
    ['SIGNUP PROCESS (New Users)'],
    ['───────────────────────────────────────────────────────────────────────────────────'],
    [''],
    ['Step 1: Fill in Your Details'],
    ['Navigate to the signup page and enter:'],
    [''],
    ['   Field                   Requirements'],
    ['   ─────────────────────  ──────────────────────────────────────────────────────'],
    ['   Full Name              Your complete name'],
    ['   Email                  Valid email address (will be verified)'],
    ['   Password               Must meet security requirements:'],
    ['                          • Minimum 8 characters'],
    ['                          • At least one uppercase letter (A-Z)'],
    ['                          • At least one lowercase letter (a-z)'],
    ['                          • At least one number (0-9)'],
    ['                          • At least one special character (!@#$%^&*)'],
    ['   Confirm Password       Must match the password exactly'],
    [''],
    ['   Example valid password: MySecure@Pass123'],
    [''],
    ['Step 2: Email Verification (OTP)'],
    ['After clicking "Send OTP":'],
    ['   1. A 6-digit OTP will be sent to your email'],
    ['   2. Check your inbox (and spam folder if needed)'],
    ['   3. Enter the 6-digit code in the verification screen'],
    ['   4. OTP expires in 10 minutes'],
    ['   5. Click "Verify OTP & Sign Up"'],
    [''],
    ['Step 3: Account Creation'],
    ['   • Your account is automatically created after OTP verification'],
    ['   • You will be redirected to the login page'],
    ['   • Use your email and password to log in'],
    [''],
    ['───────────────────────────────────────────────────────────────────────────────────'],
    ['LOGIN PROCESS (Existing Users)'],
    ['───────────────────────────────────────────────────────────────────────────────────'],
    [''],
    ['1. Navigate to the login page'],
    ['2. Enter your registered email address'],
    ['3. Enter your password'],
    ['4. Click "Login"'],
    ['5. You will be directed to the Dashboard'],
    [''],
    ['Forgot Password?'],
    ['   • Contact your system administrator'],
    ['   • Password reset functionality can be implemented if needed'],
    [''],
    ['Security Features:'],
    ['   ✓ Passwords are encrypted with bcrypt'],
    ['   ✓ Email verification prevents fake accounts'],
    ['   ✓ Session management with JWT tokens'],
    ['   ✓ Automatic logout after 7 days'],
    [''],
    ['Troubleshooting:'],
    ['   Problem: "Invalid email or password"'],
    ['   Solution: Check credentials, ensure caps lock is off'],
    [''],
    ['   Problem: "Email not verified"'],
    ['   Solution: Complete OTP verification during signup'],
    [''],
    ['   Problem: OTP not received'],
    ['   Solution: Check spam folder, request new OTP, verify email address'],
    ['']
  ];

  const wsIntro = XLSX.utils.aoa_to_sheet(introData);
  wsIntro['!cols'] = [{ wch: 100 }];
  
  // Style the title
  if (wsIntro['A1']) {
    wsIntro['A1'].s = {
      font: { bold: true, sz: 16 },
      alignment: { horizontal: 'center' }
    };
  }

  // Make the URL clickable (row 18, column A)
  if (wsIntro['A18']) {
    wsIntro['A18'].l = { Target: "https://subscription-management-6uje.onrender.com" };
    wsIntro['A18'].s = {
      font: { color: { rgb: "0563C1" }, underline: true },
      fill: { fgColor: { rgb: "FFFFFF" } }
    };
  }

  XLSX.utils.book_append_sheet(wb, wsIntro, 'Introduction & Login');

  // ===== COMPANY DETAILS SHEET =====
  const companyData = [
    ['3. COMPANY DETAILS MANAGEMENT'],
    [''],
    ['Overview:'],
    ['The Company Details section allows you to manage all aspects of your organization\'s'],
    ['information including company information, departments, employees, and subscription categories.'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['3.1 COMPANY INFORMATION'],
    [''],
    ['How to Set Up Company Information:'],
    [''],
    ['1. Navigate to "Company Details" from the sidebar'],
    ['2. Click on "Company Information" tab'],
    ['3. Fill in the following details:'],
    [''],
    ['   Field                    Description                           Required'],
    ['   ──────────────────────  ────────────────────────────────────  ──────────'],
    ['   Company Name            Legal name of your business           Yes'],
    ['   Industry                Type of business (IT, Finance, etc.)  No'],
    ['   Address                 Physical business address             No'],
    ['   City                    City name                             No'],
    ['   State/Province          State or province                     No'],
    ['   Country                 Country name                          No'],
    ['   Postal Code             ZIP/Postal code                       No'],
    ['   Phone                   Business phone number                 No'],
    ['   Email                   Business email address                No'],
    ['   Website                 Company website URL                   No'],
    ['   Default Currency        Primary currency for operations       Yes'],
    ['   Fiscal Year Start       Start month of fiscal year            No'],
    [''],
    ['4. Click "Save Changes"'],
    [''],
    ['Important Notes:'],
    ['• Default currency affects all financial calculations'],
    ['• This information appears on reports and notifications'],
    ['• Only administrators can modify company information'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['3.2 DEPARTMENTS'],
    [''],
    ['Managing Departments:'],
    [''],
    ['Add a New Department:'],
    ['   1. Click on "Department" tab'],
    ['   2. Click "+ Add Department" button'],
    ['   3. Enter department name'],
    ['   4. Select department head (optional)'],
    ['   5. Add description (optional)'],
    ['   6. Click "Save"'],
    [''],
    ['Edit Department:'],
    ['   1. Click the edit icon next to the department'],
    ['   2. Modify the information'],
    ['   3. Click "Update"'],
    [''],
    ['Delete Department:'],
    ['   1. Click the delete icon next to the department'],
    ['   2. Confirm deletion'],
    ['   ⚠️ Warning: Deleting a department does not delete associated subscriptions'],
    [''],
    ['Department Use Cases:'],
    ['• Organize subscriptions by business unit'],
    ['• Track departmental spending'],
    ['• Assign department heads for approval workflows'],
    ['• Generate department-specific reports'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['3.3 EMPLOYEES'],
    [''],
    ['Managing Employees:'],
    [''],
    ['Add Employee:'],
    ['   1. Click on "Employees" tab'],
    ['   2. Click "+ Add Employee" button'],
    ['   3. Fill in employee details:'],
    ['      • Full Name (Required)'],
    ['      • Email (Required)'],
    ['      • Department'],
    ['      • Job Title'],
    ['      • Phone Number'],
    ['      • Employee ID'],
    ['   4. Click "Save"'],
    [''],
    ['Edit Employee:'],
    ['   1. Click edit icon on employee row'],
    ['   2. Modify information'],
    ['   3. Click "Update"'],
    [''],
    ['Delete Employee:'],
    ['   1. Click delete icon on employee row'],
    ['   2. Confirm deletion'],
    [''],
    ['Employee Features:'],
    ['• Link subscriptions to specific employees'],
    ['• Track who is responsible for each subscription'],
    ['• Send renewal reminders to subscription owners'],
    ['• Generate employee-wise expense reports'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['3.4 SUBSCRIPTION CATEGORIES'],
    [''],
    ['Managing Categories:'],
    [''],
    ['Add Category:'],
    ['   1. Click on "Subscription Category" tab'],
    ['   2. Enter category name in the input field'],
    ['   3. Click "+ Add Category"'],
    [''],
    ['Common Category Examples:'],
    ['   • Software & SaaS'],
    ['   • Cloud Services'],
    ['   • Marketing Tools'],
    ['   • Communication'],
    ['   • Entertainment'],
    ['   • Utilities'],
    ['   • Insurance'],
    ['   • Licenses'],
    [''],
    ['Delete Category:'],
    ['   1. Click the trash icon next to the category'],
    ['   2. Confirm deletion'],
    [''],
    ['Important Notes:'],
    ['• Categories help organize and filter subscriptions'],
    ['• Categories are tenant-specific (isolated per company)'],
    ['• Deleting a category does not delete associated subscriptions'],
    ['• Use categories for reporting and analytics'],
    [''],
    ['Import/Export Categories:'],
    ['   • Click "Template" to download Excel template'],
    ['   • Click "Import" to upload categories from Excel'],
    ['   • Click "Export" to download current categories'],
    ['']
  ];

  const wsCompany = XLSX.utils.aoa_to_sheet(companyData);
  wsCompany['!cols'] = [{ wch: 100 }];
  XLSX.utils.book_append_sheet(wb, wsCompany, 'Company Details');

  // ===== SETUP & CONFIGURATION SHEET =====
  const configData = [
    ['4. SETUP & CONFIGURATION'],
    [''],
    ['Overview:'],
    ['The Setup & Configuration section allows you to customize system settings including'],
    ['currencies, payment methods, reminder policies, and field enablement.'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['4.1 CURRENCY MANAGEMENT'],
    [''],
    ['Adding a New Currency:'],
    [''],
    ['1. Navigate to "Setup & Configuration" from sidebar'],
    ['2. Ensure "Currency" tab is selected'],
    ['3. Click "Add Currency" button'],
    ['4. Fill in currency details:'],
    [''],
    ['   Field                   Description                           Example'],
    ['   ──────────────────────  ────────────────────────────────────  ──────────'],
    ['   Currency Code           3-letter ISO code (autocomplete)      USD, EUR, INR'],
    ['   Description             Full currency name                    United States Dollar'],
    ['   Symbol                  Currency symbol                       $, €, ₹'],
    ['   Exchange Rate           Rate against local currency           1.00, 0.85'],
    [''],
    ['5. Click "Add Currency"'],
    [''],
    ['Currency Features:'],
    ['• Autocomplete suggestions for currency codes'],
    ['• Automatic symbol and description population'],
    ['• Exchange rate tracking'],
    ['• Set local currency (LCY) in Company Information'],
    [''],
    ['Updating Exchange Rates:'],
    ['   1. Click "Update Currency" button'],
    ['   2. Modify exchange rates in the table'],
    ['   3. Click "Save Changes"'],
    ['   • Last updated timestamp is automatically recorded'],
    [''],
    ['Deleting Currency:'],
    ['   1. Click delete icon next to currency'],
    ['   2. Confirm deletion'],
    ['   ⚠️ Cannot delete currency if used in active subscriptions'],
    [''],
    ['Excel Import/Export:'],
    ['   • Download Template: Get pre-formatted Excel template'],
    ['   • Import: Upload currencies in bulk'],
    ['   • Export: Download current currency list'],
    [''],
    ['   Excel Format:'],
    ['   Column A: Currency Code (USD, EUR)'],
    ['   Column B: Description (United States Dollar)'],
    ['   Column C: Symbol ($, €)'],
    ['   Column D: Exchange Rate (1.00, 0.85)'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['4.2 PAYMENT METHODS'],
    [''],
    ['Adding Payment Method:'],
    [''],
    ['1. Click on "Payment Methods" tab'],
    ['2. Click "+ Add Payment Method" button'],
    ['3. Fill in payment method details:'],
    [''],
    ['   Field                   Description                           Options/Example'],
    ['   ──────────────────────  ────────────────────────────────────  ──────────────────'],
    ['   Title                   Payment method name                   Corporate Visa'],
    ['   Type                    Payment type                          Credit, Debit, Bank Transfer,'],
    ['                                                                  Digital Wallet, Cash, Other'],
    ['   Description             Additional details                    Company credit card for SaaS'],
    ['   Icon                    Visual identifier                     visa, mastercard, paypal, amex,'],
    ['                                                                  apple_pay, google_pay, bank, cash'],
    ['   Manager                 Person responsible                    John Doe'],
    ['   Expires At              Expiration date (if applicable)       2025-12-31'],
    ['   Financial Institution   Bank or provider name                 Chase Bank'],
    ['   Last Four Digits        Last 4 digits of card/account        1234'],
    [''],
    ['4. Click "Add Payment Method"'],
    [''],
    ['Payment Method Features:'],
    ['• Track multiple payment methods'],
    ['• Monitor expiration dates'],
    ['• See subscription count per payment method'],
    ['• Edit and delete payment methods'],
    [''],
    ['View Subscriptions by Payment Method:'],
    ['   1. Click on subscription count badge'],
    ['   2. See all subscriptions using that payment method'],
    ['   3. Quick access to subscription details'],
    [''],
    ['Excel Import/Export:'],
    ['   • Download template for bulk import'],
    ['   • Import multiple payment methods at once'],
    ['   • Export current payment methods list'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['4.3 REMINDER POLICY'],
    [''],
    ['Configuring Reminder Settings:'],
    [''],
    ['1. Click on "Reminder Policy" tab'],
    ['2. Configure reminder preferences:'],
    [''],
    ['   Setting                 Description                           Recommendation'],
    ['   ──────────────────────  ────────────────────────────────────  ──────────────────'],
    ['   Days Before Renewal     When to send reminder                 7, 14, 30 days'],
    ['   Notification Method     Email, In-app, or Both                Both (recommended)'],
    ['   Reminder Frequency      How often to send reminders           Daily, Weekly'],
    ['   Reminder Recipients     Who receives notifications            Owner, Admin, Both'],
    [''],
    ['3. Click "Save Policy"'],
    [''],
    ['Reminder Features:'],
    ['• Automatic email notifications'],
    ['• In-app notification center'],
    ['• Customizable reminder timing'],
    ['• Multiple recipients support'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['4.4 SUBSCRIPTION FIELD ENABLEMENT'],
    [''],
    ['Managing Custom Fields:'],
    [''],
    ['1. Click on "Subscription" tab'],
    ['2. View enabled/disabled fields'],
    ['3. Toggle fields on/off using checkboxes'],
    ['4. Add custom fields (Maximum 4 fields)'],
    [''],
    ['Adding Custom Field:'],
    ['   1. Enter field name in input box'],
    ['   2. Click "+ Add Field"'],
    ['   3. Field is automatically enabled'],
    ['   4. Click "Save Field Settings"'],
    [''],
    ['Field Management:'],
    ['   • Enable/disable fields as needed'],
    ['   • Delete unused custom fields'],
    ['   • Fields affect subscription form layout'],
    ['   • Maximum 4 custom fields allowed'],
    [''],
    ['Default Fields (Always Available):'],
    ['   • Service Name'],
    ['   • Amount'],
    ['   • Currency'],
    ['   • Billing Cycle'],
    ['   • Next Renewal Date'],
    ['   • Category'],
    ['   • Department'],
    ['   • Payment Method'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['4.5 COMPLIANCE FIELD ENABLEMENT'],
    [''],
    ['Managing Compliance Fields:'],
    [''],
    ['1. Click on "Compliance" tab'],
    ['2. View compliance-specific fields'],
    ['3. Toggle fields on/off'],
    ['4. Add custom compliance fields'],
    [''],
    ['Adding Compliance Field:'],
    ['   1. Enter field name'],
    ['   2. Click "+ Add Compliance Field"'],
    ['   3. Enable/disable as needed'],
    ['   4. Click "Save Compliance Settings"'],
    [''],
    ['Common Compliance Fields:'],
    ['   • License Number'],
    ['   • Regulatory Body'],
    ['   • Compliance Status'],
    ['   • Audit Date'],
    ['   • Certification Number'],
    ['   • Renewal Authority'],
    [''],
    ['']
  ];

  const wsConfig = XLSX.utils.aoa_to_sheet(configData);
  wsConfig['!cols'] = [{ wch: 100 }];
  XLSX.utils.book_append_sheet(wb, wsConfig, 'Setup & Configuration');

  // ===== SUBSCRIPTION MANAGEMENT SHEET =====
  const subscriptionData = [
    ['5. SUBSCRIPTION MANAGEMENT'],
    [''],
    ['Overview:'],
    ['Manage all your recurring subscriptions in one place. Track costs, renewal dates,'],
    ['payment methods, and get automatic reminders.'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.1 ADDING A NEW SUBSCRIPTION'],
    [''],
    ['Step-by-Step Process:'],
    [''],
    ['1. Navigate to "Subscriptions" from the sidebar'],
    ['2. Click "+ Add Subscription" button'],
    ['3. Fill in subscription details:'],
    [''],
    ['   BASIC INFORMATION'],
    ['   ────────────────────────────────────────────────────────────────────────────'],
    ['   Field                   Description                           Example'],
    ['   ──────────────────────  ────────────────────────────────────  ──────────────────'],
    ['   Service Name            Name of subscription                  Adobe Creative Cloud'],
    ['   Amount                  Subscription cost                     49.99'],
    ['   Currency                Payment currency                      USD, EUR, INR'],
    ['   Billing Cycle           Payment frequency                     Monthly, Yearly,'],
    ['                                                                  Quarterly, Weekly'],
    ['   Start Date              When subscription began               2025-01-01'],
    ['   Next Renewal            Next payment date                     2025-12-01'],
    ['   Category                Subscription type                     Software & SaaS'],
    [''],
    ['   ORGANIZATIONAL DETAILS'],
    ['   ────────────────────────────────────────────────────────────────────────────'],
    ['   Department              Which department uses it              IT, Marketing'],
    ['   Owner                   Responsible employee                  John Doe'],
    ['   Payment Method          How payment is made                   Corporate Visa'],
    [''],
    ['   ADDITIONAL INFORMATION (Optional)'],
    ['   ────────────────────────────────────────────────────────────────────────────'],
    ['   Description             Notes about subscription              Design software for team'],
    ['   Website URL             Vendor website                        adobe.com'],
    ['   Login Email             Account email                         admin@company.com'],
    ['   Contract Terms          Agreement details                     Annual contract'],
    ['   Auto-Renewal            Automatic renewal status              Yes/No'],
    ['   Cancellation Notice     Required notice period                30 days'],
    [''],
    ['4. Click "Save Subscription"'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.2 VIEWING SUBSCRIPTIONS'],
    [''],
    ['Dashboard View:'],
    ['   • Quick overview of all active subscriptions'],
    ['   • Total monthly/yearly costs'],
    ['   • Upcoming renewals'],
    ['   • Department-wise breakdown'],
    ['   • Category-wise spending'],
    [''],
    ['List View (Subscriptions Page):'],
    ['   • Complete subscription list in table format'],
    ['   • Sortable columns (click headers to sort)'],
    ['   • Filter by:'],
    ['     - Category'],
    ['     - Department'],
    ['     - Payment Method'],
    ['     - Status (Active/Cancelled)'],
    ['     - Date Range'],
    [''],
    ['Search Functionality:'],
    ['   • Search by service name'],
    ['   • Search by owner name'],
    ['   • Search by department'],
    ['   • Real-time search results'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.3 EDITING SUBSCRIPTIONS'],
    [''],
    ['How to Edit:'],
    [''],
    ['1. Locate the subscription in the list'],
    ['2. Click the "Edit" icon/button'],
    ['3. Modify the required fields'],
    ['4. Click "Update Subscription"'],
    [''],
    ['Editable Fields:'],
    ['   ✓ Amount (if price changes)'],
    ['   ✓ Currency'],
    ['   ✓ Billing Cycle'],
    ['   ✓ Next Renewal Date'],
    ['   ✓ Category'],
    ['   ✓ Department'],
    ['   ✓ Owner'],
    ['   ✓ Payment Method'],
    ['   ✓ All optional fields'],
    [''],
    ['Change History:'],
    ['   • View "Subscription History" tab'],
    ['   • See all changes made to subscription'],
    ['   • Track who made changes and when'],
    ['   • Compare previous vs current values'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.4 CANCELLING SUBSCRIPTIONS'],
    [''],
    ['Cancellation Process:'],
    [''],
    ['1. Click on the subscription'],
    ['2. Click "Cancel Subscription" button'],
    ['3. Select cancellation date'],
    ['4. Add cancellation reason (optional)'],
    ['5. Confirm cancellation'],
    [''],
    ['After Cancellation:'],
    ['   • Subscription moves to "Cancelled" status'],
    ['   • Remains visible in "Cancelled Subscriptions" view'],
    ['   • Historical data is preserved'],
    ['   • Can be restored if cancelled by mistake'],
    [''],
    ['View Cancelled Subscriptions:'],
    ['   1. Navigate to "Cancelled Subscriptions" from sidebar'],
    ['   2. See all cancelled subscriptions'],
    ['   3. Filter by cancellation date'],
    ['   4. Export cancelled subscriptions report'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.5 SUBSCRIPTION REMINDERS'],
    [''],
    ['Automatic Reminders:'],
    ['   • Email notifications before renewal dates'],
    ['   • In-app notifications in notification center'],
    ['   • Customizable timing (set in Reminder Policy)'],
    ['   • Sent to subscription owner and/or admin'],
    [''],
    ['Viewing Reminders:'],
    ['   1. Click notification bell icon (top right)'],
    ['   2. See all pending reminders'],
    ['   3. Click reminder to view subscription details'],
    ['   4. Mark as read/dismiss'],
    [''],
    ['Reminder Information Includes:'],
    ['   • Subscription name'],
    ['   • Renewal date'],
    ['   • Amount to be charged'],
    ['   • Payment method'],
    ['   • Days until renewal'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.6 EXCEL IMPORT/EXPORT'],
    [''],
    ['Exporting Subscriptions:'],
    [''],
    ['1. Go to Subscriptions page'],
    ['2. Click "Export" button'],
    ['3. Select export format (Excel recommended)'],
    ['4. Choose filters (optional):'],
    ['   • Date range'],
    ['   • Department'],
    ['   • Category'],
    ['   • Status'],
    ['5. Click "Download"'],
    [''],
    ['Export Contains:'],
    ['   • All subscription details'],
    ['   • Cost breakdowns'],
    ['   • Renewal information'],
    ['   • Owner and department'],
    ['   • Custom fields data'],
    [''],
    ['Importing Subscriptions:'],
    [''],
    ['1. Download template (click "Template" button)'],
    ['2. Fill in subscription data in Excel'],
    ['3. Required columns:'],
    ['   • Service Name'],
    ['   • Amount'],
    ['   • Currency'],
    ['   • Billing Cycle'],
    ['   • Next Renewal Date'],
    [''],
    ['4. Click "Import" button'],
    ['5. Select your Excel file'],
    ['6. Review import summary'],
    ['7. Confirm import'],
    [''],
    ['Import Tips:'],
    ['   ✓ Use provided template for correct format'],
    ['   ✓ Ensure dates are in YYYY-MM-DD format'],
    ['   ✓ Currency codes must match configured currencies'],
    ['   ✓ Categories must exist before import'],
    ['   ✓ Departments must be created first'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.7 REPORTS & ANALYTICS'],
    [''],
    ['Available Reports:'],
    [''],
    ['1. Spending Reports'],
    ['   • Total spending by period'],
    ['   • Department-wise breakdown'],
    ['   • Category-wise analysis'],
    ['   • Payment method usage'],
    [''],
    ['2. Renewal Calendar'],
    ['   • Monthly view of upcoming renewals'],
    ['   • Yearly calendar view'],
    ['   • Color-coded by category'],
    ['   • Filter by department'],
    [''],
    ['3. Cost Trends'],
    ['   • Monthly spending trends'],
    ['   • Year-over-year comparison'],
    ['   • Category growth analysis'],
    ['   • Budget vs actual'],
    [''],
    ['4. Custom Reports'],
    ['   • Create custom date ranges'],
    ['   • Select specific metrics'],
    ['   • Apply multiple filters'],
    ['   • Export to Excel/PDF'],
    [''],
    ['Accessing Reports:'],
    ['   1. Navigate to "Reports" from sidebar'],
    ['   2. Select report type'],
    ['   3. Set date range and filters'],
    ['   4. Click "Generate Report"'],
    ['   5. Export or share as needed'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['5.8 BEST PRACTICES'],
    [''],
    ['Regular Maintenance:'],
    ['   □ Review subscriptions monthly'],
    ['   □ Update renewal dates promptly'],
    ['   □ Cancel unused subscriptions'],
    ['   □ Keep payment methods current'],
    ['   □ Update exchange rates regularly'],
    [''],
    ['Cost Optimization:'],
    ['   □ Identify duplicate subscriptions'],
    ['   □ Consolidate similar services'],
    ['   □ Review annual vs monthly costs'],
    ['   □ Negotiate better rates during renewal'],
    ['   □ Track utilization and ROI'],
    [''],
    ['Data Accuracy:'],
    ['   □ Assign owners to all subscriptions'],
    ['   □ Categorize subscriptions properly'],
    ['   □ Keep contact information updated'],
    ['   □ Document cancellation procedures'],
    ['   □ Maintain audit trail'],
    [''],
    ['Team Collaboration:'],
    ['   □ Share access with department heads'],
    ['   □ Set up approval workflows'],
    ['   □ Enable reminder notifications'],
    ['   □ Schedule regular reviews'],
    ['   □ Document subscription policies'],
    [''],
    ['']
  ];

  const wsSubscription = XLSX.utils.aoa_to_sheet(subscriptionData);
  wsSubscription['!cols'] = [{ wch: 100 }];
  XLSX.utils.book_append_sheet(wb, wsSubscription, 'Subscription Management');

  // ===== TROUBLESHOOTING SHEET =====
  const troubleshootingData = [
    ['TROUBLESHOOTING & FAQ'],
    [''],
    ['Common Issues and Solutions'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['SIGNUP & LOGIN ISSUES'],
    [''],
    ['Q: I\'m not receiving the OTP email'],
    ['A: 1. Check your spam/junk folder'],
    ['   2. Verify email address is correct'],
    ['   3. Wait a few minutes and try again'],
    ['   4. Request a new OTP'],
    ['   5. Contact support if issue persists'],
    [''],
    ['Q: My OTP expired before I could use it'],
    ['A: OTPs expire after 10 minutes. Request a new OTP by going back to the signup page.'],
    [''],
    ['Q: Password doesn\'t meet requirements'],
    ['A: Ensure your password has:'],
    ['   • At least 8 characters'],
    ['   • One uppercase letter'],
    ['   • One lowercase letter'],
    ['   • One number'],
    ['   • One special character (!@#$%^&*)'],
    [''],
    ['Q: "Email already registered" error'],
    ['A: This email is already in use. Try logging in or use a different email.'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['CONFIGURATION ISSUES'],
    [''],
    ['Q: "Category already exists" error'],
    ['A: This category name is already used in your account. Choose a different name.'],
    ['   Note: Categories are tenant-specific, so other companies can have the same name.'],
    [''],
    ['Q: Cannot delete currency'],
    ['A: Currency is being used by active subscriptions. Remove currency from subscriptions first.'],
    [''],
    ['Q: Exchange rates not updating'],
    ['A: 1. Click "Update Currency" button'],
    ['   2. Modify rates in the table'],
    ['   3. Click "Save Changes"'],
    ['   4. Check "Last Updated" timestamp'],
    [''],
    ['Q: Payment method not showing in dropdown'],
    ['A: Ensure payment method is saved and page is refreshed. Check if payment method was deleted.'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['SUBSCRIPTION MANAGEMENT ISSUES'],
    [''],
    ['Q: Subscription not appearing in list'],
    ['A: 1. Check if filters are applied'],
    ['   2. Verify subscription was saved successfully'],
    ['   3. Refresh the page'],
    ['   4. Check if viewing correct tenant/account'],
    [''],
    ['Q: Reminders not being received'],
    ['A: 1. Check notification settings'],
    ['   2. Verify email address in profile'],
    ['   3. Check spam folder'],
    ['   4. Ensure reminder policy is configured'],
    ['   5. Verify subscription has future renewal date'],
    [''],
    ['Q: Cannot import Excel file'],
    ['A: 1. Use provided template'],
    ['   2. Ensure file format is .xlsx or .xls'],
    ['   3. Check all required fields are filled'],
    ['   4. Verify date format is YYYY-MM-DD'],
    ['   5. Ensure currencies/categories exist'],
    [''],
    ['═══════════════════════════════════════════════════════════════════════════════════'],
    [''],
    ['SUPPORT & CONTACT'],
    [''],
    ['Technical Support:'],
    ['   • Email: support@subscriptiontracker.com'],
    ['   • Response time: Within 24 hours'],
    [''],
    ['Documentation:'],
    ['   • User Guide: This document'],
    ['   • Video Tutorials: Available on website'],
    ['   • Knowledge Base: help.subscriptiontracker.com'],
    [''],
    ['Feature Requests:'],
    ['   • Submit via: feedback@subscriptiontracker.com'],
    ['   • Include detailed description'],
    ['   • Explain use case and benefit'],
    [''],
    ['Bug Reports:'],
    ['   • Email: bugs@subscriptiontracker.com'],
    ['   • Include:'],
    ['     - Steps to reproduce'],
    ['     - Expected vs actual behavior'],
    ['     - Screenshots (if applicable)'],
    ['     - Browser and version'],
    ['']
  ];

  const wsTroubleshooting = XLSX.utils.aoa_to_sheet(troubleshootingData);
  wsTroubleshooting['!cols'] = [{ wch: 100 }];
  XLSX.utils.book_append_sheet(wb, wsTroubleshooting, 'Troubleshooting & FAQ');

  // Save the workbook
  const outputPath = path.join(__dirname, '..', 'Subscription_Tracker_User_Guide.xlsx');
  XLSX.writeFile(wb, outputPath);
  
  console.log(`✅ User Guide created successfully: ${outputPath}`);
  console.log('\nGuide includes:');
  console.log('  1. Introduction & Login/Signup Process');
  console.log('  2. Company Details Management');
  console.log('  3. Setup & Configuration');
  console.log('  4. Subscription Management');
  console.log('  5. Troubleshooting & FAQ');
}

generateUserGuide();
