import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { PieChart, List, Settings, FileText, User, Bell, Building2 } from "lucide-react";
var navItems = [
    { path: "/", label: "Dashboard", icon: PieChart },
    { path: "/subscriptions", label: "Subscriptions", icon: List },
    { path: "/compliance", label: "Compliance", icon: Settings },
    { path: "/notifications", label: "Notifications", icon: Bell },
    { path: "/reminders", label: "Setup & Configuration", icon: Settings },
    { path: "/company-details", label: "Company Details", icon: Building2 },
    { path: "/reports", label: "Reports", icon: FileText },
    // ...removed User Management link...
];
export default function Sidebar() {
    // Get current location for active state
    var location = window.location.pathname;
    return (_jsxs("aside", { className: "w-64 bg-gradient-to-br from-gray-50 via-white to-gray-100 shadow-lg flex flex-col h-screen border-r border-gray-200 relative overflow-hidden font-sans", children: [_jsx("div", { className: "absolute inset-0 opacity-5", children: _jsx("div", { className: "absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2MCIgaGVpZ2h0PSI2MCIgdmlld0JveD0iMCAwIDYwIDYwIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGZpbGw9IiM0RjQ2RTUiIGQ9Ik0zNiAzNGMtMy4zMTQgMC02LTIuNjg2LTYtNnMyLjY4Ni02IDYtNiA2IDIuNjg2IDYgNi0yLjY4NiA2LTYgNnptMCAxOGMtMy4zMTQgMC02LTIuNjg2LTYtNnMyLjY4Ni02IDYtNiA2IDIuNjg2IDYgNi0yLjY4NiA2LTYgNnptMTgtMGMtMy4zMTQgMC02LTIuNjg2LTYtNnMyLjY4Ni02IDYtNiA2IDIuNjg2IDYgNi0yLjY4NiA2LTYgNnptMTggMThjLTMuMzE0IDAtNi0yLjY4Ni02LTZzMi42ODYtNiA2LTYgNiAyLjY4NiA2IDYtMi42ODYgNi02IDZ6Ii8+PC9nPjwvc3ZnPg==')] bg-repeat" }) }), _jsx("div", { className: "p-6 border-b border-gray-200 relative z-10", children: _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("img", { src: "/assets/logo.png", alt: "SubsTracker Logo", className: "w-10 h-10 object-contain" }), _jsx("h1", { className: "text-xl font-bold bg-gradient-to-r from-pink-600 via-indigo-600 to-blue-600 bg-clip-text text-transparent tracking-tight animate-gradient leading-tight", children: "SubsTracker" })] }) }), _jsx("nav", { className: "flex-1 p-4 overflow-y-auto relative z-10", children: _jsx("ul", { className: "space-y-1", children: navItems.map(function (item) {
                        var Icon = item.icon;
                        var isActive = location === item.path;
                        return (_jsx("li", { children: _jsxs(Link, { to: item.path, className: "\n                  group relative flex items-center gap-3 px-4 py-3 rounded-lg \n                  transition-all duration-300 overflow-hidden\n                  ".concat(isActive
                                    ? 'bg-indigo-50 text-indigo-700 font-semibold shadow-sm'
                                    : 'text-gray-700 hover:bg-gray-50 hover:text-gray-900', "\n                "), children: [_jsx("div", { className: "\n                    absolute left-0 top-0 bottom-0 w-0 bg-gradient-to-r from-indigo-500/20 to-indigo-400/10\n                    transition-all duration-500 ease-out\n                    ".concat(isActive ? 'w-full' : 'group-hover:w-full', "\n                  ") }), _jsx(Icon, { size: 20, className: "\n                      ".concat(isActive ? 'text-indigo-600' : 'text-gray-500 group-hover:text-indigo-600', " \n                      transition-colors duration-300 z-10 flex-shrink-0\n                    ") }), _jsx("span", { className: "text-sm font-medium transition-all duration-300 group-hover:translate-x-2 z-10 tracking-tight", children: item.label }), isActive && (_jsx("div", { className: "ml-auto w-1.5 h-6 bg-indigo-500 rounded-full animate-pulse" }))] }) }, item.path));
                    }) }) }), _jsx("div", { className: "p-4 border-t border-gray-200 relative z-10", children: _jsxs("div", { className: "flex items-center gap-3 p-3 rounded-lg bg-gray-50 hover:bg-gray-100 transition-all duration-300 cursor-pointer group", children: [_jsxs("div", { className: "relative transition-transform duration-300 group-hover:scale-110 flex-shrink-0", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-r from-indigo-500 to-blue-500 rounded-full flex items-center justify-center shadow-md animate-pulse", children: _jsx(User, { className: "text-white", size: 18 }) }), _jsx("div", { className: "absolute bottom-0 right-0 w-3 h-3 bg-green-500 rounded-full border-2 border-white animate-ping" })] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-semibold text-gray-900 group-hover:text-indigo-700 transition-colors duration-300 truncate", children: "John Doe" }), _jsx("p", { className: "text-xs font-medium text-gray-500 group-hover:text-gray-700 transition-colors duration-300 truncate", children: "Administrator" })] }), _jsx("div", { className: "text-gray-400 group-hover:text-gray-600 transition-all duration-300 group-hover:rotate-180 flex-shrink-0", children: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-5 w-5", viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { fillRule: "evenodd", d: "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", clipRule: "evenodd" }) }) })] }) }), _jsx("style", { children: "\n        @keyframes gradient {\n          0% { background-position: 0% 50%; }\n          50% { background-position: 100% 50%; }\n          100% { background-position: 0% 50%; }\n        }\n        .animate-gradient {\n          background-size: 200% auto;\n          animation: gradient 3s ease infinite;\n        }\n        \n        /* Improve font rendering */\n        aside {\n          -webkit-font-smoothing: antialiased;\n          -moz-osx-font-smoothing: grayscale;\n          text-rendering: optimizeLegibility;\n        }\n      " })] }));
}
