import {
  X,
  BookOpen,
  Download,
  LayoutDashboard,
  Settings,
  Building2,
  Users,
  Layers,
  RefreshCw,
  ShieldCheck,
  Bell,
  FileUp,
  BarChart3,
  CheckCircle2,
  Sparkles,
} from "lucide-react";

interface DocsModalProps {
  open: boolean;
  onClose: () => void;
}

type DocsStat = { label: string; value: string };

type DocsBlock =
  | { type: "hero"; text: string }
  | { type: "p"; text: string }
  | { type: "tip"; text: string }
  | { type: "step"; number: string; heading: string; text: string }
  | { type: "checklist"; items: string[] }
  | { type: "highlight"; heading: string; items: string[] }
  | { type: "stats"; items: DocsStat[] };

type DocsSection = {
  id: string;
  icon: typeof Sparkles;
  color: string;
  badgeClass: string;
  badgeLabel: string;
  title: string;
  subtitle: string;
  content: DocsBlock[];
};

const sections: DocsSection[] = [
  {
    id: "overview",
    icon: Sparkles,
    color: "from-indigo-600 to-violet-500",
    badgeClass: "bg-indigo-100 text-indigo-700",
    badgeLabel: "Overview",
    title: "Welcome to Trackla",
    subtitle: "Subscription tracking, compliance, and renewals — in one workspace",
    content: [
      {
        type: "hero",
        text: "Trackla is built to help teams manage subscriptions, track renewals, and stay compliant with clear ownership and timely reminders.",
      },
      {
        type: "p",
        text: "This guide matches the screens in your app: Dashboard, Subscriptions, Compliance, Renewals (Government Licenses), Notifications, Setup & Configuration, Company Details, and Reports.",
      },
      {
        type: "highlight",
        heading: "Main Modules",
        items: [
          "Dashboard — KPIs and what needs attention",
          "Subscriptions — SaaS/service spend with renewal dates",
          "Compliance — compliance records, ledger, and logs",
          "Renewals — government licenses with expiry tracking",
          "Notifications — reminders generated from dates and policies",
          "Setup & Configuration — currencies, payment methods, custom fields",
          "Company Details — company info, departments, employees, user management",
          "Reports — spend and renewal reporting",
        ],
      },
      {
        type: "stats",
        items: [
          { label: "Guide Version", value: "May 2026" },
          { label: "Focus", value: "Accuracy" },
          { label: "Goal", value: "No missed renewals" },
        ],
      },
    ],
  },
  {
    id: "dashboard",
    icon: LayoutDashboard,
    color: "from-slate-700 to-slate-900",
    badgeClass: "bg-slate-100 text-slate-700",
    badgeLabel: "Dashboard",
    title: "Dashboard",
    subtitle: "Your daily overview: spend, renewals, and compliance",
    content: [
      {
        type: "p",
        text: "Use the dashboard as your daily control center. It summarizes spend and surfaces upcoming renewals and reminders so nothing gets missed.",
      },
      {
        type: "checklist",
        items: [
          "Review upcoming renewals and expired items",
          "Check notifications generated by reminder policies",
          "Spot changes and anomalies using history/audit views",
        ],
      },
      {
        type: "tip",
        text: "Make sure every subscription has a Next Renewal Date and Responsible Person — those two fields drive most reminders and accountability.",
      },
    ],
  },
  {
    id: "setup",
    icon: Settings,
    color: "from-blue-600 to-indigo-600",
    badgeClass: "bg-blue-100 text-blue-700",
    badgeLabel: "Setup",
    title: "Initial Setup",
    subtitle: "Configure company, users, and core lists",
    content: [
      {
        type: "p",
        text: "Complete these steps once per company (tenant). This keeps reporting consistent and makes data entry faster.",
      },
      {
        type: "step",
        number: "1",
        heading: "Company Details",
        text: "Go to Company Details → Company Information. Confirm Company Name and LCY (local currency). LCY is used for consolidated reporting and LCY Amount calculations.",
      },
      {
        type: "step",
        number: "2",
        heading: "Departments and Employees",
        text: "Add departments (Company Details → Department) and employees (Company Details → Employees). Subscriptions and renewals can be assigned to departments and responsible people.",
      },
      {
        type: "step",
        number: "3",
        heading: "Users and Access",
        text: "Use Company Details → User Management to manage who can access the company. If you have access to multiple companies, use the sidebar company switcher to change the active tenant.",
      },
      {
        type: "step",
        number: "4",
        heading: "Setup & Configuration",
        text: "Go to Setup & Configuration to maintain master data like Currency, Payment Methods, and Custom Fields. Keeping these clean reduces import and reporting issues.",
      },
      {
        type: "tip",
        text: "Use consistent naming for departments and categories so reports group correctly (avoid duplicates like “IT” vs “I.T.”).",
      },
    ],
  },
  {
    id: "company",
    icon: Building2,
    color: "from-violet-600 to-purple-600",
    badgeClass: "bg-violet-100 text-violet-700",
    badgeLabel: "Company",
    title: "Company Details",
    subtitle: "People, departments, and user management",
    content: [
      {
        type: "highlight",
        heading: "Company Details Pages",
        items: [
          "Company Information",
          "Department",
          "Employees",
          "Subscription Category",
          "User Management",
        ],
      },
      {
        type: "p",
        text: "These lists power assignments across subscriptions and renewals. For best results, keep employees up to date and always assign a Responsible Person (and optional Secondary Person) on time-sensitive records.",
      },
    ],
  },
  {
    id: "subscriptions",
    icon: Layers,
    color: "from-purple-600 to-pink-500",
    badgeClass: "bg-purple-100 text-purple-700",
    badgeLabel: "Subscriptions",
    title: "Subscriptions",
    subtitle: "Add, import, and manage recurring spend",
    content: [
      {
        type: "p",
        text: "Subscriptions is where you track every SaaS tool or recurring payment. Accurate dates and ownership are essential for renewals, reminders, and audit history.",
      },
      {
        type: "highlight",
        heading: "Key Fields (Subscription Form)",
        items: [
          "Service Name (unique)",
          "Vendor and Website",
          "Currency, Amount per Unit, Quantity, Total Amount, Tax",
          "Start Date, Billing Cycle, Next Renewal Date",
          "Reminder Days and Reminder Policy",
          "Responsible Person and Secondary Person",
          "Department (multi-select) and Category",
          "Status (Active/Trial/Draft/Cancelled)",
          "Notes and Documents",
        ],
      },
      {
        type: "step",
        number: "1",
        heading: "Add Manually",
        text: "Go to Subscriptions → + Add Subscription. Fill the required fields, confirm Next Renewal Date, set Reminder Days, and assign a Responsible Person.",
      },
      {
        type: "step",
        number: "2",
        heading: "LCY Amount and Multi-currency",
        text: "If you bill in multiple currencies, Trackla calculates LCY Amount for consistent reporting. Keep currency exchange rates accurate in configuration.",
      },
      {
        type: "tip",
        text: "Use date format YYYY-MM-DD when importing. A valid Next Renewal Date is required for reminders and auto-renewal to work correctly.",
      },
    ],
  },
  {
    id: "autoRenewal",
    icon: RefreshCw,
    color: "from-orange-500 to-red-500",
    badgeClass: "bg-orange-100 text-orange-700",
    badgeLabel: "Renewals",
    title: "Auto Renewal (Subscriptions)",
    subtitle: "How it works and how to test it",
    content: [
      {
        type: "p",
        text: "Auto Renewal is optional. Enable it only for subscriptions you want to renew automatically on the Next Renewal Date.",
      },
      {
        type: "checklist",
        items: [
          "Enable Auto Renewal",
          "Set Status = Active",
          "Set Next Renewal Date to a valid date (YYYY-MM-DD)",
          "Confirm Billing Cycle (Monthly/Quarterly/Yearly/Weekly)",
        ],
      },
      {
        type: "tip",
        text: "When auto-renewal triggers, Trackla updates the cycle dates and logs the change in Subscription History (shows “Auto Renewed”).",
      },
    ],
  },
  {
    id: "govLicenses",
    icon: ShieldCheck,
    color: "from-emerald-600 to-teal-600",
    badgeClass: "bg-emerald-100 text-emerald-700",
    badgeLabel: "Renewals",
    title: "Renewals (Government Licenses)",
    subtitle: "Track expiry dates, fees, and responsible owners",
    content: [
      {
        type: "p",
        text: "The Renewals page (Government Licenses) is used to track licenses/permits with expiry dates and renewal fees. Set ownership and reminder lead times so teams can renew on time.",
      },
      {
        type: "highlight",
        heading: "Key Fields (Renewal / License Form)",
        items: [
          "Renewal Name/Title (unique)",
          "Issuing Authority, Issue Date, Expiry Date",
          "Renewal Fee, Currency, LCY Amount",
          "Renewal Cycle Time and Lead Time Estimate",
          "Responsible Person and Secondary Person",
          "Department and Status (Active/Expired/Cancelled)",
        ],
      },
      {
        type: "tip",
        text: "Set Expiry Date carefully — it drives reminders and “expired renewals” reporting.",
      },
    ],
  },
  {
    id: "notifications",
    icon: Bell,
    color: "from-amber-500 to-orange-500",
    badgeClass: "bg-amber-100 text-amber-700",
    badgeLabel: "Notifications",
    title: "Notifications",
    subtitle: "Your operational inbox for reminders and alerts",
    content: [
      {
        type: "p",
        text: "Notifications are generated from subscription renewal dates and renewal/license expiry dates. Use this page daily to manage what needs action.",
      },
      {
        type: "checklist",
        items: [
          "Upcoming subscription renewals",
          "Government license expiry reminders",
          "Compliance-related reminders (when configured)",
        ],
      },
      {
        type: "tip",
        text: "If notifications look empty, verify Status is Active and the relevant date fields are valid.",
      },
    ],
  },
  {
    id: "importExport",
    icon: FileUp,
    color: "from-slate-600 to-slate-700",
    badgeClass: "bg-slate-100 text-slate-700",
    badgeLabel: "Import/Export",
    title: "Import & Export",
    subtitle: "Onboard quickly and keep data consistent",
    content: [
      {
        type: "p",
        text: "Use Import/Export to migrate from spreadsheets or to perform bulk updates. Keep date and naming formats consistent to avoid reporting duplication.",
      },
      {
        type: "step",
        number: "1",
        heading: "Import",
        text: "Download the template, fill your data, and upload. Fix validation errors before confirming.",
      },
      {
        type: "step",
        number: "2",
        heading: "Export",
        text: "Export is useful for audits, reconciliation, and bulk edits. After re-import, review Subscription History to confirm the changes.",
      },
      {
        type: "tip",
        text: "Recommended date format: YYYY-MM-DD for Start Date, Next Renewal Date, Issue Date, and Expiry Date.",
      },
    ],
  },
  {
    id: "reports",
    icon: BarChart3,
    color: "from-cyan-600 to-blue-600",
    badgeClass: "bg-sky-100 text-sky-700",
    badgeLabel: "Reports",
    title: "Reports",
    subtitle: "Spend, renewals, and compliance visibility",
    content: [
      {
        type: "p",
        text: "Reports help you understand spend, upcoming renewals, and operational workload across departments. Use LCY-based reporting for consistent totals.",
      },
      {
        type: "highlight",
        heading: "Common Reports",
        items: [
          "Spending Analysis",
          "Card-wise Spend",
          "Upcoming Renewals and Expired Renewals",
          "Department-wise Renewals",
          "Renewal Lead Time Analysis",
          "Compliance Scorecard (by department)",
          "Upcoming Filings",
        ],
      },
      {
        type: "tip",
        text: "Keep departments and categories clean in Company Details so report grouping stays accurate.",
      },
    ],
  },
  {
    id: "users",
    icon: Users,
    color: "from-fuchsia-600 to-violet-600",
    badgeClass: "bg-fuchsia-100 text-fuchsia-700",
    badgeLabel: "Users",
    title: "Users & Permissions",
    subtitle: "Roles, ownership, and accountability",
    content: [
      {
        type: "p",
        text: "Keep owners and responsible people accurate. It improves reminders, accountability, and auditability across subscriptions and renewals.",
      },
      {
        type: "checklist",
        items: [
          "Assign Responsible Person on subscriptions and licenses",
          "Use Secondary Person for backup coverage",
          "Use User Management to control tenant access",
          "Switch active company using the sidebar switcher when needed",
        ],
      },
    ],
  },
];

function RenderContent({ content }: { content: DocsBlock[] }) {
  return (
    <div className="space-y-4">
      {content.map((block, i) => {
        switch (block.type) {
          case "hero":
            return (
              <div key={i} className="rounded-2xl border border-indigo-100 bg-gradient-to-br from-indigo-50 to-violet-50 p-4 sm:p-5">
                <p className="text-sm sm:text-[15px] leading-relaxed text-slate-700">{block.text}</p>
              </div>
            );
          case "p":
            return (
              <p key={i} className="text-sm sm:text-[15px] leading-relaxed text-slate-600">
                {block.text}
              </p>
            );
          case "tip":
            return (
              <div key={i} className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4 sm:p-5 flex gap-3">
                <span className="text-base leading-none">💡</span>
                <p className="text-sm leading-relaxed text-indigo-900/90">{block.text}</p>
              </div>
            );
          case "highlight":
            return (
              <div key={i} className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5">
                <p className="text-xs font-semibold tracking-wide text-slate-500 uppercase mb-3">{block.heading}</p>
                <ul className="space-y-2">
                  {block.items.map((item, j) => (
                    <li key={j} className="flex items-start gap-2">
                      <CheckCircle2 className="h-4 w-4 text-indigo-500 mt-0.5 flex-shrink-0" />
                      <span className="text-sm text-slate-700 leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            );
          case "stats":
            return (
              <div key={i} className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {block.items.map((item, j) => (
                  <div key={j} className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                    <p className="text-[11px] font-semibold tracking-wide text-slate-500 uppercase">{item.label}</p>
                    <p className="mt-1 text-base font-bold text-slate-900">{item.value}</p>
                  </div>
                ))}
              </div>
            );
          case "checklist":
            return (
              <ul key={i} className="space-y-2">
                {block.items.map((item, j) => (
                  <li key={j} className="flex items-start gap-2">
                    <CheckCircle2 className="h-4 w-4 text-indigo-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-slate-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            );
          case "step":
            return (
              <div key={i} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-5 flex gap-3">
                <div className="h-9 w-9 rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 text-white flex items-center justify-center text-xs font-extrabold flex-shrink-0">
                  {block.number}
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-bold text-slate-900 mb-1">{block.heading}</p>
                  <p className="text-sm text-slate-600 leading-relaxed">{block.text}</p>
                </div>
              </div>
            );
          default:
            return null;
        }
      })}
    </div>
  );
}

export default function DocsModal({ open, onClose }: DocsModalProps) {
  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[9999] bg-slate-900/60 backdrop-blur-sm p-4 sm:p-6 flex items-center justify-center"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="w-full max-w-3xl max-h-[calc(100vh-3rem)] bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col">
        <div className="px-6 sm:px-7 py-5 bg-gradient-to-r from-indigo-600 to-violet-600 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="h-11 w-11 rounded-xl bg-white/15 flex items-center justify-center text-white">
              <BookOpen className="h-5 w-5" />
            </div>
            <div className="min-w-0">
              <h2 className="text-white font-heading font-extrabold text-lg sm:text-xl leading-tight truncate">Trackla Documentation</h2>
              <p className="text-white/80 text-xs sm:text-sm leading-tight">Getting Started Guide</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <a
              href="/docs/Trackla-Getting-Started-Guide.pdf"
              download
              className="h-9 px-3 rounded-xl bg-white/15 hover:bg-white/25 transition-colors inline-flex items-center justify-center gap-2 text-white text-sm font-semibold whitespace-nowrap"
              aria-label="Download documentation"
            >
              <Download className="h-4 w-4" />
              <span className="hidden sm:inline">Download</span>
            </a>
            <button
              type="button"
              onClick={onClose}
              className="h-9 w-9 rounded-xl bg-white/15 hover:bg-white/25 transition-colors flex items-center justify-center text-white"
              aria-label="Close documentation"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto px-6 sm:px-7 py-6 sm:py-7 space-y-10">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <div key={section.id}>
                <div className="flex items-start gap-3 sm:gap-4 mb-5">
                  <div className={`h-12 w-12 rounded-2xl bg-gradient-to-br ${section.color} text-white flex items-center justify-center shadow-sm flex-shrink-0`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <h3 className="font-heading text-lg sm:text-xl font-extrabold text-slate-900 leading-snug">{section.title}</h3>
                    <p className="text-sm text-slate-500 leading-relaxed">{section.subtitle}</p>
                  </div>
                </div>

                <div className="border-t border-slate-100 mb-5" />
                <RenderContent content={section.content} />
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
